### ISSUE TITLE
repository broken?

### ISSUE THREAD

**Issue by gailkaiser** [Programming-Systems-Lab/chroniclerj#2]
I asked a prospective project student to fork chroniclerj on github and see if he could get running, and this is what he says:

Thank you so much for the quick reply! I'm sorry to bother you again but I am interested in giving this project a try, so I forked ChroniclerJ to my own repository. The readme mentioned two shell scripts (unpackLibs.sh and makeJar.sh) but I can't locate them. Also, the link to the runnable binary leads to a 404 error. If you have the time, could you let me know where the scripts exist so that I can build the project?

**Comment by hustc12** [comment]
The README file has already been updated by Jonathan Bell, so this issue has been resolved.

**Comment by asn10038** [comment]
Appears to be resolved 1+ year later. Closing issue.
